/**
 * AI Service Provider Abstraction.
 * Interfaces with Google Gemini API with model fallback, response validation, timeout control, and safe logging.
 */

const DEFAULT_AI_MODEL = process.env.AI_MODEL || "gemini-2.5-flash";
const FALLBACK_MODELS = ["gemini-2.5-flash", "gemini-3.1-flash-lite", "gemini-flash-latest"];
const API_TIMEOUT_MS = 25000; // 25 seconds timeout

/**
 * Strips code fences and parses JSON safely.
 */
function sanitizeAndParseJson(rawText) {
  if (!rawText || typeof rawText !== "string") {
    throw new Error("Empty or invalid AI response received.");
  }

  let cleaned = rawText.trim();

  // Remove markdown codeblock fences if present
  if (cleaned.startsWith("```json")) {
    cleaned = cleaned.replace(/^```json\s*/, "").replace(/\s*```$/, "");
  } else if (cleaned.startsWith("```")) {
    cleaned = cleaned.replace(/^```\s*/, "").replace(/\s*```$/, "");
  }

  cleaned = cleaned.trim();

  try {
    return JSON.parse(cleaned);
  } catch (err) {
    // Attempt extracting JSON substring
    const firstBrace = cleaned.indexOf("{");
    const lastBrace = cleaned.lastIndexOf("}");
    if (firstBrace !== -1 && lastBrace !== -1 && lastBrace > firstBrace) {
      const extracted = cleaned.substring(firstBrace, lastBrace + 1);
      return JSON.parse(extracted);
    }
    throw new Error(`Failed to parse AI JSON response: ${err.message}`);
  }
}

/**
 * Validates that the AI response matches the expected Health Summary schema.
 */
function validateHealthSummaryOutput(data) {
  if (!data || typeof data !== "object") {
    throw new Error("AI output is not a valid JSON object.");
  }

  return {
    overallSummary: typeof data.overallSummary === "string" ? data.overallSummary : "Summary unavailable.",
    recentHealth: typeof data.recentHealth === "string" ? data.recentHealth : "Recent clinical evaluation not documented.",
    medications: Array.isArray(data.medications) ? data.medications : [],
    vitals: Array.isArray(data.vitals) ? data.vitals : [],
    upcomingCare: typeof data.upcomingCare === "string" ? data.upcomingCare : "No upcoming appointments scheduled.",
    doctorDiscussionPoints: Array.isArray(data.doctorDiscussionPoints) ? data.doctorDiscussionPoints : [],
  };
}

/**
 * Executes a single generation attempt against a specific model.
 */
async function callGeminiEndpoint(modelName, apiKey, systemInstruction, userPrompt) {
  const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${apiKey}`;

  const payload = {
    contents: [
      {
        role: "user",
        parts: [{ text: `${systemInstruction}\n\n${userPrompt}` }],
      },
    ],
    generationConfig: {
      temperature: 0.2,
      topP: 0.8,
      maxOutputTokens: 1500,
      responseMimeType: "application/json",
    },
  };

  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), API_TIMEOUT_MS);

  try {
    const response = await fetch(endpoint, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(payload),
      signal: controller.signal,
    });

    clearTimeout(timeoutId);

    if (!response.ok) {
      const errorBody = await response.text().catch(() => "");
      console.warn(`[AI Service] Model ${modelName} returned HTTP ${response.status}: ${errorBody.slice(0, 120)}`);
      throw new Error(`AI model ${modelName} returned HTTP status ${response.status}`);
    }

    const data = await response.json();
    const candidateText = data?.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!candidateText) {
      throw new Error(`No response text generated by model ${modelName}.`);
    }

    const parsed = sanitizeAndParseJson(candidateText);
    return validateHealthSummaryOutput(parsed);
  } catch (error) {
    clearTimeout(timeoutId);
    throw error;
  }
}

/**
 * Core AI generation method with multi-model automatic fallback.
 */
async function generateHealthSummaryWithGemini({ systemInstruction, userPrompt }) {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY is not configured on the server.");
  }

  const primaryModel = process.env.AI_MODEL || DEFAULT_AI_MODEL;
  const modelsToTry = Array.from(new Set([primaryModel, ...FALLBACK_MODELS]));

  const startTime = Date.now();
  let lastError = null;

  for (const model of modelsToTry) {
    try {
      console.log(`[AI Service] Generating health summary with model: ${model}`);
      const result = await callGeminiEndpoint(model, apiKey, systemInstruction, userPrompt);
      const duration = Date.now() - startTime;
      console.log(`[AI Service] Health summary successfully generated with ${model} in ${duration}ms`);
      return result;
    } catch (err) {
      console.warn(`[AI Service] Model ${model} failed (${err.message}). Trying fallback...`);
      lastError = err;
    }
  }

  console.error(`[AI Service] All AI model attempts failed. Last error: ${lastError?.message}`);
  throw new Error("Unable to generate health summary at this time. Please try again in a moment.");
}

module.exports = {
  generateHealthSummaryWithGemini,
};
